server:
  port: 8989
management:
  metrics:
    export:
      statsd:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers

info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@build.number@'
    java:
      version: '@java.version@'