/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bhuang.avro.model;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Student {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Student\",\"namespace\":\"com.bhuang.avro.model\",\"types\":[{\"type\":\"record\",\"name\":\"StudentEntity\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"age\",\"type\":\"int\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends Student {
    public static final org.apache.avro.Protocol PROTOCOL = com.bhuang.avro.model.Student.PROTOCOL;
  }
}